# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7505272fe2dd9c5518d81e78ab6019e537d99af0a6a471c9cd76d40adf330c6892960b4dc3cceea88160d647432273f2054f2fcd67a1cb94c9fe645ecd096842

test:
  secret_key_base: 2191c7e44335197a95f8ef5e7a5e8ff3e6937fef4f9ef57bbc36d38d0c66d0561147fde65ec47eaee8336f2c18d1d34a6eb1f4a75fb28c2b717d2eff79a3e547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
